[package]

name = "rustOver"
version = "0.0.1"
authors = [ "Andre Schurer <aschurer@alienlabs.eu>" ]

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"  # if you're using `derive(RustcDecodable)`
hyper = "0.7.2"
